fabulous-dev/Fabulous.Avalonia

samples/CounterApp/App.fs, src/Fabulous.Avalonia/Platform/iOS/FabulousAvaloniaAppDelegate.fs, src/Fabulous.Avalonia/Views/Application.fs, src/Fabulous.Avalonia/Views/Styles/FluentTheme.fs
This PR prevents a crash by settings the theme to light for now as we figure out how to manage how to properly support styles :)
=> Use light theme for now to test more controls in Avalonia

samples/CounterApp/App.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Views/Controls/DatePicker.fs
=> DatePicker wrapper

src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Views/Controls/Separator.fs
=> Separator wrapper

samples/CounterApp/App.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/CheckBox.fs
* Add wrapper for CheckBox control
* Add Checkbox sample in CounterApp
Love your Fabulous projects! This is just a simple addition, but I'd be happy to contribute more if I might be of help.
=> CheckBox control

Fabulous.Avalonia.sln, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj
This removes a hardcoded relative path to Fabulous
=> Use Fabulous 2.2 preview one

samples/Gallery/Gallery.fsproj, samples/Gallery/Overview.fs, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/PathIcon.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/PathIcon.fs, src/Fabulous.Avalonia/Widgets/Controls/_IconElement.fs
=> Path Icon Wrapper + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/Platform/Android/SplashActivity.fs, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/AutoCompleteBox.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/AutoCompleteBox.fs
=> AutoCompleteBox Wrapper + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/Expander.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Expander.fs
=> Expander Wrapper + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/ToolTip.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Tooltip.fs
=> Tooltip Wrapper + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/ViewBox.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Shapes/Ellipse.fs, src/Fabulous.Avalonia/Widgets/Controls/Viewbox.fs
=> ViewBox Wrapper + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/Popup.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Primitives/Popup.fs
=> Popup wrapper + Sample

samples/Gallery/App.fs, samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/UniformGrid.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Panels/UniformGrid.fs
=> UniformGrid + Sample

samples/Gallery/App.fs, samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/TabControl.fs, samples/Gallery/Widgets/TabStrip.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/TabStrip.fs, src/Fabulous.Avalonia/Widgets/Controls/TabStripItem.fs
=> Tab controls + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/Calendar.fs, samples/Gallery/Widgets/CalendarDatePicker.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Calendar.fs, src/Fabulous.Avalonia/Widgets/Controls/CalendarDatePicker.fs
=> Calendar Wrappers

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/ButtonSpinner.fs, samples/Gallery/Widgets/PathIcon.fs, samples/Gallery/Widgets/RadioButton.fs, samples/Gallery/Widgets/Slider.fs, samples/Gallery/Widgets/SplitButton.fs, samples/Gallery/Widgets/TickBar.fs, samples/Gallery/Widgets/ToggleButton.fs, samples/Gallery/Widgets/ToggleSplitButton.fs, samples/Gallery/Widgets/ToggleSwitch.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/ButtonSpinner.fs, src/Fabulous.Avalonia/Widgets/Controls/DataValidationErrors.fs, src/Fabulous.Avalonia/Widgets/Controls/RadioButton.fs, src/Fabulous.Avalonia/Widgets/Controls/Slider.fs, src/Fabulous.Avalonia/Widgets/Controls/SplitButton.fs, src/Fabulous.Avalonia/Widgets/Controls/TickBar.fs, src/Fabulous.Avalonia/Widgets/Controls/ToggleButton.fs, src/Fabulous.Avalonia/Widgets/Controls/ToggleSplitButton.fs, src/Fabulous.Avalonia/Widgets/Controls/ToggleSwitch.fs, src/Fabulous.Avalonia/Widgets/Controls/_Spinner.fs
=> Spinners wrappers

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/ComboBox.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/ComboBox.fs, src/Fabulous.Avalonia/Widgets/Controls/ComboBoxItem.fs
=> ComboBox Wrapper + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/MenuFlyout.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets.fs, src/Fabulous.Avalonia/Widgets/Controls/Button.fs, src/Fabulous.Avalonia/Widgets/Controls/MenuFlyout.fs, src/Fabulous.Avalonia/Widgets/Controls/MenuItem.fs, src/Fabulous.Avalonia/Widgets/Controls/Primitives/_FlyoutBase.fs, src/Fabulous.Avalonia/Widgets/Controls/SplitButton.fs
=> MenuFlyout Wrappers

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/CheckBox.fs, samples/Gallery/Widgets/ContextMenu.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/CheckBox.fs, src/Fabulous.Avalonia/Widgets/Controls/ContextMenu.fs, src/Fabulous.Avalonia/Widgets/Controls/MenuItem.fs, src/Fabulous.Avalonia/Widgets/Controls/_TemplatedControl.fs
=> ContextMenu wrapper

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/MaskedTextBox.fs, src/Fabulous.Avalonia/Widgets/Controls/MaskedTextBox.fs
Add TextChanged message to MaskedTextBox constructor (to match the TextBox behavior)
Add MaskedTextBox sample to Gallery
=> MaskedTextBox updates

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/DockPanel.fs, samples/Gallery/Widgets/Menu.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Menu.fs, src/Fabulous.Avalonia/Widgets/Controls/MenuItem.fs, src/Fabulous.Avalonia/Widgets/Controls/Panels/DockPanel.fs, src/Fabulous.Avalonia/Widgets/Controls/_ItemsControl.fs
=> Menu Wrapper + Sample

samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/Border.fs, samples/Gallery/Widgets/Canvas.fs, src/Fabulous.Avalonia/Widgets/Controls/Panels/Canvas.fs
=> Canvas + Border + Samples

samples/Gallery/App.fs, samples/Gallery/Widgets/ListBox.fs, src/Fabulous.Avalonia/VirtualizedCollection.fs, src/Fabulous.Avalonia/Widgets/Controls/ListBox.fs
Fixes https://github.com/fabulous-dev/Fabulous.Avalonia/issues/77
=> Removed padding around the inner control and two selectable layers 

samples/Gallery/App.fs, samples/Gallery/Widgets/Button.fs, samples/Gallery/Widgets/CheckBox.fs, samples/Gallery/Widgets/ContextMenu.fs, samples/Gallery/Widgets/DropDownButton.fs, samples/Gallery/Widgets/Menu.fs, samples/Gallery/Widgets/RadioButton.fs, samples/Gallery/Widgets/RepeatButton.fs, samples/Gallery/Widgets/SplitButton.fs, samples/Gallery/Widgets/StackPanel.fs, samples/Gallery/Widgets/ToggleButton.fs, samples/Gallery/Widgets/ToggleSplitButton.fs, samples/Gallery/Widgets/ToggleSwitch.fs, src/Fabulous.Avalonia/Attributes.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Button.fs, src/Fabulous.Avalonia/Widgets/Controls/ButtonSpinner.fs, src/Fabulous.Avalonia/Widgets/Controls/CheckBox.fs, src/Fabulous.Avalonia/Widgets/Controls/DropDownButton.fs, src/Fabulous.Avalonia/Widgets/Controls/RadioButton.fs, src/Fabulous.Avalonia/Widgets/Controls/RepeatButton.fs, src/Fabulous.Avalonia/Widgets/Controls/SplitButton.fs, src/Fabulous.Avalonia/Widgets/Controls/ToggleButton.fs, src/Fabulous.Avalonia/Widgets/Controls/ToggleSplitButton.fs, src/Fabulous.Avalonia/Widgets/Controls/ToggleSwitch.fs
In this PR . Im looking at update Button Widget constructors and remove some unnecessary modifiers
Fixes  #78
=> Button updates

samples/Gallery/App.fs, samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/Carousel.fs, samples/Gallery/Widgets/Carousel2.fs, samples/Gallery/Widgets/ListBox.fs, samples/Gallery/Widgets/ListBox2.fs, samples/Gallery/Widgets/ListBox3.fs, src/Fabulous.Avalonia/Attributes.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Program.fs, src/Fabulous.Avalonia/Widgets/Controls/Carousel.fs, src/Fabulous.Avalonia/Widgets/Controls/ListBox.fs, src/Fabulous.Avalonia/Widgets/Controls/_SelectingItemsControl.fs
Notes: 
Need to investigate why `onSelectedIndexChanged` and `selectedIndex` does not work and produce a crash in Fabulous 
https://user-images.githubusercontent.com/31915729/215292220-045225ec-1e84-43ab-a0be-9f8840804218.mp4
=> Carousel Widget + Modifier + Sample

samples/Gallery/App.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/ExperimentalAcrylicBorder.fs, src/Fabulous.Avalonia/Widgets/Controls/ExperimentalAcrylicMaterial.fs
=> ExperimentalAcrylicBorder Wrapper + Widget

samples/Gallery/App.fs, samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/LayoutTransformControl.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Widgets/Controls/Border.fs, src/Fabulous.Avalonia/Widgets/Controls/LayoutTransformControl.fs
=> LayoutTransformControl Widget + Sample

samples/Gallery/App.fs, samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/ThemeAware.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Program.fs, src/Fabulous.Avalonia/ThemeAware.fs, src/Fabulous.Avalonia/Widgets/Application.fs, src/Fabulous.Avalonia/Widgets/Controls/ThemeVariantScope.fs, src/Fabulous.Avalonia/Widgets/Styling/_StyledElement.fs
Cancel and replace #89 
https://user-images.githubusercontent.com/6429007/219612655-7a213931-aea0-43a1-b338-e2607f92b461.mov
=> Support for Theme awareness

samples/CounterApp/App.fs, samples/Gallery/App.fs, samples/Gallery/Gallery.fsproj, samples/Gallery/WidgetPage.fs, samples/Gallery/Widgets/AcrylicPage.fs, samples/Gallery/Widgets/AdornerLayer.fs, samples/Gallery/Widgets/Clipping.fs, samples/Gallery/Widgets/LayoutTransformControl.fs, samples/Gallery/Widgets/Panel.fs, samples/Gallery/Widgets/ScrollViewer.fs, samples/Gallery/Widgets/Slider.fs, samples/Gallery/Widgets/Transforms.fs, samples/Gallery/Widgets/ViewBox.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Views/Controls/ExperimentalAcrylicBorder.fs, src/Fabulous.Avalonia/Views/Controls/ExperimentalAcrylicMaterial.fs, src/Fabulous.Avalonia/Views/Controls/Primitives/_RangeBase.fs, src/Fabulous.Avalonia/Views/Controls/Slider.fs, src/Fabulous.Avalonia/Views/Panels/Panel.fs
=> Acrylic Sample

Directory.Packages.props, samples/Gallery/Pages/AutoCompleteBoxPage.fs, samples/Gallery/Pages/ContextMenuPage.fs, samples/Gallery/Pages/ListBoxPage.fs, samples/Gallery/Pages/State.fs, samples/Gallery/Pages/TabControlPage.fs, samples/Gallery/Pages/Types.fs, samples/Gallery/Pages/View.fs, samples/Gallery/Root/MainWindow.fs, samples/Gallery/Root/State.fs, samples/Gallery/Root/Types.fs, src/Fabulous.Avalonia.Themes.Fluent/Fabulous.Avalonia.Themes.Fluent.fsproj, src/Fabulous.Avalonia.targets, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Views/Controls/AutoCompleteBox.fs, src/Fabulous.Avalonia/Views/Controls/MaskedTextBox.fs, src/Fabulous.Avalonia/Views/Controls/Primitives/_RangeBase.fs, src/Fabulous.Avalonia/Views/Controls/RefreshVisualizer.fs, src/Fabulous.Avalonia/Views/Controls/TextBox.fs, src/Fabulous.Avalonia/Views/Imaging/Image.fs, src/Fabulous.Avalonia/Views/Layouts/ScrollViewer.fs, src/Fabulous.Avalonia/Views/Media/Geometries/PolylineGeometry.fs, src/Fabulous.Avalonia/Views/Menu/ContextMenu.fs, src/Fabulous.Avalonia/Views/Menu/MenuFlyout.fs, src/Fabulous.Avalonia/Views/_InputElement.fs, src/Fabulous.Avalonia/Views/_ItemsControl.fs, src/Fabulous.Avalonia/Views/_SelectingItemsControl.fs, src/Fabulous.Avalonia/Views/_TopLevel.fs, src/Fabulous.Avalonia/Views/_WindowBase.fs, src/Fabulous.Avalonia/VirtualizedCollection.fs
http://fuget.org/packages/Avalonia/11.0.0-preview7/lib/netstandard2.0/diff/11.0.0-preview6/
=> See what is broken in the new preview7

samples/Gallery/Gallery.fsproj, samples/Gallery/NavigationTypes.fs, samples/Gallery/Pages/Animations/AnimationsPage.fs, samples/Gallery/Pages/Animations/ImplicitCanvasAnimationsPage.fs, samples/Gallery/Root/MainWindow.fs, samples/Gallery/Root/NaviagtionState.fs, src/Fabulous.Avalonia/Views/_StyledElement.fs
=> Implicit animations sample

samples/Gallery/Gallery.fsproj, samples/Gallery/NavigationTypes.fs, samples/Gallery/Pages/ClipboardPage.fs, samples/Gallery/Root/MainWindow.fs, samples/Gallery/Root/NaviagtionState.fs
Porting the Clipboard sample from https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/ClipboardPage.xaml.cs
=> Clipboard sample

samples/Gallery/Gallery.fsproj, samples/Gallery/NavigationTypes.fs, samples/Gallery/Pages/DragAndDropPage.fs, samples/Gallery/Root/MainWindow.fs, samples/Gallery/Root/NaviagtionState.fs, src/Fabulous.Avalonia/Attributes.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Views/_DragDrop.fs
This PR adds support for Drag and Drop functionality: 
- Adds a new `defineRoutedEvent`
- DragDrop modifiers
- Ported sample from https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/DragAndDropPage.xaml.cs
=> Drag and Drop support

samples/Gallery/Pages/ClipboardPage.fs, samples/Gallery/Pages/DialogsPage.fs, samples/Gallery/Pages/DragAndDropPage.fs, samples/Gallery/Pages/NotificationsPage.fs, samples/Gallery/Root/MainView.fs, samples/Gallery/Root/MainWindow.fs, samples/Gallery/Root/State.fs, samples/Gallery/Root/Types.fs, samples/TicTacToe/App.fs, src/Fabulous.Avalonia/Application.fs
- ClipBoard
- StorageProvider
- WindowNotificationManager
- InsetsManager
- PlatformSettigns
- FocusManager
=> Add FabApplication Helpers

Directory.Packages.props, samples/Fabulous.Avalonia.Samples.targets, samples/RenderDemo/Styles/Transitions.xaml, samples/RenderDemo/TransitionsPage.fs, src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj, src/Fabulous.Avalonia/Views/Controls/NotificationCard.fs, src/Fabulous.Avalonia/Views/Styling/Transition.fs, templates/content/blank/.template.config/template.json
https://github.com/AvaloniaUI/Avalonia/compare/11.0.4...11.0.5
=> AvaloniaUI 11.0.5

samples/Gallery/App.fs, samples/Gallery/Platform/Android/MainActivity.fs, samples/Gallery/Platform/Desktop/Program.fs, samples/Gallery/Platform/iOS/SceneDelegate.fs, samples/RenderDemo/App.fs, samples/RenderDemo/Platform/Android/MainActivity.fs, samples/RenderDemo/Platform/Desktop/Program.fs, samples/RenderDemo/Platform/iOS/SceneDelegate.fs, src/Fabulous.Avalonia/Application.fs, src/Fabulous.Avalonia/Platform/iOS/FabSceneDelegate.fs, templates/content/blank/App.fs, templates/content/blank/Platform/Android/MainActivity.fs, templates/content/blank/Platform/Desktop/Program.fs, templates/content/blank/Platform/iOS/SceneDelegate.fs, templates/content/multi/NewApp.Android/MainActivity.fs, templates/content/multi/NewApp.Android/NewApp.Android.fsproj, templates/content/multi/NewApp.Browser/NewApp.Browser.fsproj, templates/content/multi/NewApp.Browser/Program.fs, templates/content/multi/NewApp.Desktop/NewApp.Desktop.fsproj, templates/content/multi/NewApp.Desktop/Program.fs, templates/content/multi/NewApp.iOS/NewApp.iOS.fsproj, templates/content/multi/NewApp.iOS/SceneDelegate.fs, templates/content/multi/NewApp/App.fs, templates/content/multi/NewApp/NewApp.fsproj
Tried to improve the styling and also fix the Browser template.
Styling is very mysterious tbh. Applying the theme in the AppBuilder works, but not as part of the view function... 🙃 
Browser template is still black screen even after the changes
=> Better styling

.github/workflows/build.yml, CHANGELOG.md, README.md, templates/content/multi/NewApp.sln, templates/content/multi/NewApp/App.fs
Turned out I was just using the wrong lifetime for Browser 😄
=> Fix black screen in multi-project template when targeting Browser

.github/workflows/release.yml, Directory.Packages.props, Fabulous.Avalonia.sln, samples/Gallery/App.xaml, samples/Gallery/Gallery.fsproj, samples/Gallery/HamburgerMenu.fs, samples/Gallery/Pages/ColorPickerPage.fs, samples/Gallery/State.fs, samples/Gallery/Types.fs, src/Fabulous.Avalonia.ColorPicker/CHANGELOG.md, src/Fabulous.Avalonia.ColorPicker/ColorPicker.fs, src/Fabulous.Avalonia.ColorPicker/ColorPreviewer.fs, src/Fabulous.Avalonia.ColorPicker/ColorSlider.fs, src/Fabulous.Avalonia.ColorPicker/ColorSpectrum.fs, src/Fabulous.Avalonia.ColorPicker/ColorView.fs, src/Fabulous.Avalonia.ColorPicker/Fabulous.Avalonia.ColorPicker.fsproj, src/Fabulous.Avalonia.ColorPicker/README.md
https://www.nuget.org/packages/Avalonia.Controls.ColorPicker
=> ColorPicker widget

templates/content/multi/NewApp.Browser/AppBundle/main.js
https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/242
=> Replace runMainAndExit with runMain

samples/Gallery/Pages/NotificationsPage.fs
- cleans up a few things left over in #225
- renames a message and
- layouts and labels the custom notification position selection
=> Notification sample cleanup

samples/Playground/App.fs
=> Components Playground

src/Fabulous.Avalonia/AppBuilderExtensions.fs, src/Fabulous.Avalonia/Application.fs, src/Fabulous.Avalonia/Attributes.fs, src/Fabulous.Avalonia/Program.fs, src/Fabulous.Avalonia/Views/Controls/Documents/_Inline.fs, src/Fabulous.Avalonia/Views/Controls/TextBlock.fs, src/Fabulous.Avalonia/Views/Controls/ToggleSwitch.fs, src/Fabulous.Avalonia/Views/ItemsControl.fs, src/Fabulous.Avalonia/Views/Menu/MenuFlyout.fs, src/Fabulous.Avalonia/Views/_Animatable.fs
Using operators is slightly slower.
=> Improve null comparisons

extensions/Fabulous.Avalonia.Diagnostics/DevTools.fs, samples/Gallery/MainWindow.fs, samples/Playground/App.fs, samples/RenderDemo/MainWindow.fs, samples/RenderDemo/RenderDemo.fsproj
=> AttachDevTools

src/Fabulous.Avalonia/Views/_StyledElement.fs
=> making new function to add inline style available as extension
