- src/Fabulous.Avalonia/Views/Controls/Slider.fs
- src/Fabulous.Avalonia/Views/Controls/_RangeBase.fs
Seems like when you extend any control in Avalonia you need to use 
```fsharp
interface IStyleable with
member this.StyleKey = typeof<Slider>
```
So the control can use its specific style 
https://user-images.githubusercontent.com/31915729/202919137-5bbf75bb-d5bd-40fc-b786-429f159d9eaf.mp4
> Use IStyleable to fix the Slider not showing on screen

- src/Fabulous.Avalonia/Attributes.fs
- src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj
- src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
Note that the Value property is of type Nullable<decimal>, since the underlying Avalonia control was recently reworked to treat an empty entry as null (https://github.com/AvaloniaUI/Avalonia/pull/8259). 
In a Fabulous context, is a nullable Value property the desired behavior for this control? Unlike the Date and Time picker controls, a non-nullable value for NumericUpDown cannot be enforced solely by the constructor, since the user has the option to manually clear the input via keyboard entry. (Note also that watermark visibility is contingent on the Value property being nullable.)
> Add NumericUpDown control

- samples/Gallery/App.fs
- src/Fabulous.Avalonia/Widgets.fs
- src/Fabulous.Avalonia/Widgets/Controls/ListBox.fs
Noticed an issue with the ListBox.
Every time you select a different item on the ListBox, it was triggering ItemSelected twice: one with the correct item selected, one with index = -1.
I tracked it down to the `ListBox.ItemsSource<'T>` attribute definition.
It looks like the generic type is actually creating a new attribute definition on every single access instead of reusing the right definition; which in turn lead Fabulous to think we were unsetting the previous attribute to set a new one when actually it's the same value.
Fabulous would clear the ListBox items, which would trigger SelectedItemChanged to -1.
To fix it, I removed the generic typing of the ItemsSource attribute definition.
Like this the attribute definition stays stable.
> Fix multiple attribute registrations for same ListBox_Items

- Fabulous.Avalonia.sln
- samples/Gallery/App.fs
- src/Fabulous.Avalonia.Tests/Fabulous.Avalonia.Tests.fsproj
- src/Fabulous.Avalonia.Tests/Generators.fs
- src/Fabulous.Avalonia.Tests/Library.fs
- src/Fabulous.Avalonia.Tests/Setup.fs
- src/Fabulous.Avalonia.Tests/ViewHelperTests.fs
- src/Fabulous.Avalonia/Program.fs
Fixes #58 
When switching from Text to Inlines, Fabulous will create all the inlines before setting Text to an empty string. Unfortunately when setting any Text value, Avalonia will clear our the freshly created inlines making Fabulous go out of sync which later will result in a crash.
To avoid this, we don't reuse TextBlocks when switching from Text to Inlines, or Inlines to Text.
> Do not reuse TextBlock if widget switches between Text and Inlines to define the text

- samples/Gallery/App.fs
- samples/Gallery/Gallery.fsproj
- samples/Gallery/WidgetPage.fs
- samples/Gallery/Widgets/ListBox.fs
- src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj
- src/Fabulous.Avalonia/VirtualizedCollection.fs
- src/Fabulous.Avalonia/Widgets.fs
- src/Fabulous.Avalonia/Widgets/Controls/ListBox.fs
The template function was not being applied to ListBox ItemSource, so it was only rendering correctly if the ItemSource was a collection of item display strings (for any other item type, the ListBox would render the internal string representation of the object rather than the conversion defined by the template function).
In this commit, the ListBox  correctly displays items for templates functions with a string output (perhaps the most common use case?).
However, it does not presently work for a template function with a ListBoxItem output. I've left some commented out code in Controls/ListBox.fs to demonstrate the present limitation. This template renders an internal string representation of the compiled ListBoxItem widget rather than the widget itself. I suspect for a ListBoxItem …
> Apply template for ListBox ItemsSource

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
Microsoft just released dotnet 7.0.102 and they apparently decided to do a breaking change and prevent people from installing the `net-ios` and `net-android` workloads 7.0.49...
This PR removes the `--from-rollback-file` flag from the `dotnet workload install` step in the build CI. This will let `dotnet` installs the latest `net-ios` and `net-android` versions, hoping it will not crash 🤞
> Remove rollback flag from dotnet workload install

- src/Fabulous.Avalonia/Views/Controls/Border.fs
- src/Fabulous.Avalonia/Views/Controls/Calendar.fs
- src/Fabulous.Avalonia/Views/Controls/Documents/TextDecoration.fs
- src/Fabulous.Avalonia/Views/Controls/Documents/_TextElement.fs
- src/Fabulous.Avalonia/Views/Controls/SelectableTextBlock.fs
- src/Fabulous.Avalonia/Views/Controls/Shapes/_Shape.fs
- src/Fabulous.Avalonia/Views/Controls/TextBlock.fs
- src/Fabulous.Avalonia/Views/Controls/TextBox.fs
- src/Fabulous.Avalonia/Views/Controls/TickBar.fs
- src/Fabulous.Avalonia/Views/Layouts/SliptView.fs
- src/Fabulous.Avalonia/Views/Media/Drawing/DrawingGroup.fs
- src/Fabulous.Avalonia/Views/Media/Drawing/GeometryDrawing.fs
- src/Fabulous.Avalonia/Views/Media/Drawing/GlyphRunDrawing.fs
- src/Fabulous.Avalonia/Views/Media/Pen.fs
- src/Fabulous.Avalonia/Views/Menu/ComboBox.fs
- src/Fabulous.Avalonia/Views/_Panel.fs
- src/Fabulous.Avalonia/Views/_TemplatedControl.fs
- src/Fabulous.Avalonia/Views/_TopLevel.fs
- src/Fabulous.Avalonia/Views/_Visual.fs
We need to add an escape hatch to ensure that we can use transitions/ animation at the main widget level: 
- Using the `SolidColorBrush` widget does not work with transitions
```fsharp
Border()
.style(borderTestStyle)
.background(SolidColorBrush(Colors.Red)
.onPointerEnter(OnPointerEnter)
.onPointerExited(OnPointerExited)
.transitions() {
BrushTransition(Border.BackgroundProperty, TimeSpan.FromSeconds(0.5))
}
```
But, if we use ` .background(Brushes. Red)` works as expected. So to allow this, we are allowing to use any `IBrush.`
> Add IBrush Escape Hatch

- README.md
- samples/CounterApp/CounterApp.fsproj
- samples/DrawingApp/DrawingApp.fsproj
- samples/Gallery/Gallery.fsproj
- samples/GameOfLife/GameOfLife.fsproj
- samples/TicTacToe/TicTacToe.fsproj
- src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj
- templates/content/blank/NewApp.fsproj
net7.0-ios is currently not available on Linux. Currently the project template user has to manually remove it on his local development machine. This PR automatically excludes net7.0-ios on Linux hosts during build time.
> Exclude 'net7.0-ios' from build on Linux to make it buildable there

- samples/CounterApp/App.fs
- samples/Gallery/Widgets/AcrylicPage.fs
- samples/Gallery/Widgets/AdornerLayer.fs
- samples/Gallery/Widgets/LayoutTransformControl.fs
- samples/Gallery/Widgets/Slider.fs
- samples/Gallery/Widgets/Transforms.fs
- samples/Gallery/Widgets/ViewBox.fs
- src/Fabulous.Avalonia/Views/Controls/Primitives/_RangeBase.fs
- src/Fabulous.Avalonia/Views/Controls/Slider.fs
- templates/content/blank/App.fs
We need to have Min and Max update the Value simultaneously to ensure that the values are correct and prevent crashes.
- We can use this when you only care about the value, and the value changes and use what is default values
```fsharp
static member inline Slider<'msg>(value: float, onValueChanged: float -> 'msg) =
WidgetBuilder<'msg, IFabSlider>(
Slider.WidgetKey,
RangeBase.Value.WithValue(value),
RangeBase.ValueChanged.WithValue(ValueEventData.create value (fun args -> onValueChanged args |> box))
)
```
- We can use this when you want to specify the min, max, value and listen fro the value changes
```fsharp
static member inline Slider<'msg>(min: float, max: float, value: float, onValueChanged: float -> 'msg) =
WidgetBuilder<'msg, IFabSlider>(
Slider.WidgetKey, …
```
> Revert to use Minimum Maximum as part of the constructor

- samples/CounterApp/CounterApp.fsproj
- samples/DrawingApp/DrawingApp.fsproj
- samples/Gallery/Gallery.fsproj
- samples/GameOfLife/GameOfLife.fsproj
- samples/TicTacToe/TicTacToe.fsproj
Fix warnings of the form
`runtimeconfig.template.json : warning XA0101: @(Content) build action is not supported`
when (initially) building the repository.
> Fix 'runtimeconfig.template.json : warning XA0101: @(Content) build action is not supported' warnings.

- templates/content/blank/NewApp.fsproj
Building projects created via the the Fabulous.Avalonia templates result in warnings of the form
`[NU1504] Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: FSharp.Core 7.0.0, FSharp.Core 7.0.0.`
This seems to be caused by (or related to) [this dotnet/fsharp issue](https://github.com/dotnet/fsharp/issues/14441).
Respective warnings in the Fabulous.Avalonia repo itself are avoided by setting DisableImplicitFSharpCoreReference to true in the  [Directory.Build.props](https://github.com/fabulous-dev/Fabulous.Avalonia/blob/main/Directory.Build.props) file. This pull request sets it in the templates project as well.
> Fix "Duplicate 'PackageReference' items found." warnings in templates project.

- samples/Gallery/Pages/TextBlockPage.fs
As I understand it the URI `avares://Gallery/Assets/Fonts#Source Sans Pro` determines the location of the embedded font family files and the name of the font family (as described in the font files) separated by the #.
The results don't look very different from the default font but they are, especially if the font size is increased.
Tested on Android and iOS.
> Fix Source Sans Pro font family reference in Gallery app TextBlock page.

- templates/content/multi/NewApp.Browser/AppBundle/index.html
- templates/content/multi/NewApp.Browser/AppBundle/main.js
From .Net 8.0, Avalonia.Browser places .js framework files in './_framework/'
Note that Avalonia.Browser v.11.0.5 does not support .Net 8.0 (v.11.0.5 is the latest build on nuget.org as of 2023-12-03).
However, .Net 8.0 is supported in Avalonia.Browser v.11.1.999, available now on the AvaloniaUI nightly build package source (https://nuget-feed-nightly.avaloniaui.net/v3/index.json)
> Browser Template: Update path for JavaScript framework files for .Net 8.0

- templates/content/multi/NewApp.Browser/AppBundle/app.css
- templates/content/multi/NewApp.Browser/AppBundle/index.html
- templates/content/multi/NewApp.Browser/AppBundle/main.js
While https://github.com/fabulous-dev/Fabulous.Avalonia/pull/194 was the right fix for net8. It seems that Avalonia 11.0.6 did a workaround/hack to prevent users from having to change the paths.
> Fix for multi-proj template

- samples/Gallery/Pages/CalendarPage.fs
- samples/Gallery/Pages/NotificationsPage.fs
- samples/Gallery/Pages/ThemeAwarePage.fs
- samples/Gallery/Pages/ToggleButtonPage.fs
- samples/Gallery/Pages/TreeViewPage.fs
- samples/Gallery/Pages/UniformGridPage.fs
Fixes #221 
This PR shows a sample of how to dispatch asynchronsly  multiple msgs inside of `Cmd.ofEffect` without having to use `Dispatcher.UIThread.Post` inside of it.
- Init and update should be able to run on any thread
- It is not recommended to access UI-related stuff from either init or update for that exact same reason
- The correct approach is to push back the access to those UI stuff in Cmd, and then make sure those Cmd run on the UI thread if required
This will queue up msgs/notifications that will be dispatched by the Fabulous runner as they are completed
```fsharp
let notifyAsyncStatusUpdates () =
Cmd.ofEffect(fun dispatch ->
async {
dispatch(NotifyInfo "started")
do! Async.Sleep(1000)
dispatch(NotifyInfo "5")
do! Async.Sleep 1000
dispatch(NotifyInfo "4")
do! Async.Sleep 1000 …
```
> Sample of how to use the dispatch function handed to me by Cmd.ofEffect

- samples/Gallery/Pages/AutoCompleteBoxPage.fs
- samples/Gallery/Pages/DialogsPage.fs
- src/Fabulous.Avalonia/Views/Controls/AutoCompleteBox.fs
Includes 
- some documentation fixes and improvements for the `AutoCompleteBox` and
- raises a question concerning the `value` parameter of the Builders not being set on the input on initial render - am I misinterpreting it and have a wrong expectation or is this a bug?
> Auto complete fixes

- samples/Gallery/Gallery.fsproj
- samples/Gallery/Pages/TreeView/SimpleTreeView.fs
- samples/Gallery/Pages/TreeView/TreeViewWithNodeInteraction.fs
- samples/Gallery/Pages/TreeViewPage.fs
- src/Fabulous.Avalonia/Views/Panels/WrapPanel.fs
Hey Fabulous Avalonia team!
On this branch I'm trying to extend the existing `TreeViewPage` example with some interactivity and as an example chose to count clicks per node and display the count while also preserving the node expansion of the tree. I'm failing with one or the other in different implementations.
Could you please have a look at it and share your thoughts or suggest changes? You'll find my different attempts in my commit history, what works and doesn't with each in the respective message.
Thanks a bunch!
> How to implement a TreeView with node changes?

- samples/Gallery/Pages/AutoCompleteBoxPage.fs
- src/Fabulous.Avalonia/BindingExtensions.fs
- src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj
- src/Fabulous.Avalonia/Views/Controls/AutoCompleteBox.fs
Hey Fabulous Avalonia team,
in this PR I've **refactored multi-binding** a property into a generic and that of the `AutoCompleteBox.ValueMemberBinding` into a specific extension allowing to set the format and property names used in the `MultiBinding` and its `Converter` easily.
I also added an **example of a remote-filtered async search** to raise an issue about some erratic behaviour I noticed:
_**If you try completely new search terms in quick succession, you'll notice that the dropdown sometimes gets populated with results for your previous searches.**_ You'll find some debugging in place that hopefully helps demonstrate what happens.
Thank you for your consideration!
> Remote-filtered async search

- Directory.Packages.props
- samples/Gallery/Gallery.fsproj
- samples/Gallery/MainWindow.fs
- samples/Gallery/Pages/TreeView/EditableTreeView.fs
- samples/Gallery/Pages/TreeView/TreeViewWithNodeInteraction.fs
- samples/Gallery/Pages/TreeViewPage.fs
- samples/Gallery/Styles/EditableTreeView.xaml
- samples/Playground/App.fs
- samples/Playground/Playground.fsproj
- src/Fabulous.Avalonia/Application.fs
- src/Fabulous.Avalonia/Fabulous.Avalonia.fsproj
In this PR I'm trying to raise a few questions and issues I encountered while working with the `TreeView` and `AutoCompleteBox` widgets.
It adds a third tab hosting a sample of an editable `TreeView` to the `Gallery` app's `TreeViewPage` that features **adding, removing, renaming and filtering items while preserving tree node expansion**. While I got that working, the solution involves a XAML style with a Binding that I don't like much.
As a follow-up to https://github.com/fabulous-dev/Fabulous.Avalonia/discussions/231, it includes a working example of **focusing** an added `TextBox` - but trying the same on an `AutoCompleteBox` **doesn't seem to work** unless hitting a magic breakpoint during debugging. See commit [changing input to AutoCompleteBox, breaking …
> Adding a sample for an editable TreeView

- templates/content/blank/.template.config/template.json
- templates/content/blank/App.fs
- templates/content/blank/NewApp.fsproj
- templates/content/multi/.template.config/template.json
- templates/content/multi/NewApp/App.fs
- templates/content/multi/NewApp/NewApp.fsproj
> Implement #118

- samples/Gallery/Pages/StylesPage.fs
- samples/Gallery/Pages/TreeView/EditableTreeView.fs
- samples/RenderDemo/Animations/AnimationsPage.fs
- samples/RenderDemo/TransitionsPage.fs
- src/Fabulous.Avalonia/Views/_StyledElement.fs
This PR enables **adding inline `IStyle`** instances to any `StyledElement`, allowing you to **write styles in a strongly-typed manner** without .xaml files - even down to the [selectors](https://docs.avaloniaui.net/docs/reference/styles/style-selector-syntax).
```f#
let private coloredTextBoxWatermark (color: IBrush) =
let style = Style(_.OfType<TextBox>().Template().OfType<TextBlock>().Name("PART_Watermark"))
style.Setters.Add(Setter(Avalonia.Controls.TextBlock.ForegroundProperty, box color))
style
let view () =
AutoCompleteBox([]).inlineStyles(coloredTextBoxWatermark(Brushes.Crimson))
```
It includes
- **an example** that uses the new extension to style an `AutoCompleteBox` in a way that neither the Fabulous nor Avalonia API would otherwise allow for.
- **an unrelated fix** for the …
> Strongly-typed inline styles

- samples/Gallery/Pages/NotificationsPage.fs
- samples/Gallery/Widgets.fs
Dear Fabulous team,
I was exploring the Avalonia `WindowNotificationManager` to see whether it supports rendering notifications with custom content and found the following alternative `Show` methods accepting an `object content` argument that looks like it could be what I'm looking for:
https://github.com/AvaloniaUI/Avalonia/blob/88bfecbee03f1bddbcc193b1890c9ac0665b6b2f/src/Avalonia.Controls/Notifications/WindowNotificationManager.cs#L96-L177
Can they be used to render content from a `WidgetBuilder`? In this PR I try to add a working example for that - including buttons that interop with the MVU program. But I get stuck at creating the view. I don't understand Fabulous enough to know how to get hold of the `EnvironmentContext` and `ViewTreeContext` I need (or an `IViewNode` to borrow them …
> Custom notification content
